# Generated by Django 5.1 on 2024-08-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_name",
            new_name="order_number",
        ),
    ]
